name = "ephemeral-scores"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "ephemeral-scores"
database_id = "d0464353-818b-41aa-9e00-49c1ddcf79a7"
